version: '3.3'

networks:
  haf-bridge:
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/24"

volumes:
  pgdata:
    driver: local

services:
  nginx:
    image:          nginx:latest
    hostname:       haf_nginx
    container_name: haf_nginx
    restart:        unless-stopped
    volumes:
      - ./src:/var/www/app
      - ./.docker/nginx:/etc/nginx/conf.d
    tty:            true
    depends_on:
      - php
    ports:
      - 45670:80
    networks:
      haf-bridge:
        ipv4_address: "10.10.0.2"

  php:
    image:          fpm
    hostname:       haf_php
    container_name: haf_php
    restart:        unless-stopped
    tty:            true
    working_dir:    /var/www/app
    depends_on:
      - cache
      - postgres
    volumes:
      - ./src:/var/www/app
      - ./.docker/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      haf-bridge:
        ipv4_address: "10.10.0.3"

  postgres:
    image:          postgres:latest
    hostname:       haf_psql
    container_name: haf_psql
    restart:        unless-stopped
    ports:
      - 45671:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=haf
      - POSTGRES_DB=haf
    networks:
      haf-bridge:
        ipv4_address: "10.10.0.4"

  cache:
    container_name: haf_cache
    restart: always
    image: redis:latest
    networks:
      haf-bridge:
        ipv4_address: "10.10.0.5"
